# Generated by Django 3.0.3 on 2020-05-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_funcionario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemDeChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.Categoria')),
            ],
            options={
                'verbose_name': 'Mensagem de chamado',
                'verbose_name_plural': 'Mensagens de chamado',
            },
        ),
    ]
