# Generated by Django 3.0.3 on 2020-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_mensagemdechamado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemDeChamado',
        ),
    ]
